spring.application.name=gestion-municipal

spring.datasource.url=jdbc:postgresql://localhost:5433/tributos_municipales
spring.datasource.username=tributo
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080